[project]
name = "dotify"
version = "0.1.0"
description = "System config manager"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotify-lib",
    "rich>=15.0.0",
]

[tool.uv.sources]
dotify-lib = { path = "lib", editable = true }

[project.scripts]
dotify = "dotify.cli:main"

[build-system]
requires = ["uv_build>=0.9.5,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.15.11",
    "ty>=0.0.31",
]
