# Virtual project

[tool.uv.workspace]
members = [
    "app",
    "lib",
]


[project]
name = "dotify"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotify-app",
    "dotify-lib",
]

[tool.uv.sources]
dotify-app = { workspace = true }
dotify-lib = { workspace = true }


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
packages = ["app", "lib"]
